---
title: "Week 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(remotes)
library(sf)
library(leaflet)
install_github("yonghah/esri2sf")
library(esri2sf)

epa_zoning <- esri2sf("https://services8.arcgis.com/0IC8hha3hgQkmGoa/arcgis/rest/services/EastPaloAltoZoning_2021_WFL1/FeatureServer/1")

smc_exemption <- read_csv("https://datahub.smcgov.org/api/views/pmvw-bs84/rows.csv?accessType=DOWNLOAD")
```

## R Markdown

```{r cars, include=FALSE}
epa_exemption <- smc_exemption %>% 
  mutate(
    APN = `Parcel Number` %>% 
      str_replace_all("-","")
  ) %>% 
  filter(APN %in% epa_zoning$APN) %>% 
  left_join(epa_zoning) %>% 
  # could have instead done right_join
  st_as_sf() %>% 
  filter(New_Zone == "R-LD")
```


```{r pressure, echo=FALSE}
leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = epa_exemption %>% 
      filter(`Fiscal Year` == "2018/2019"),
    fillColor = "yellow",
    color = "black",
    weight = 0.5
  ) %>%
addPolygons(
  data = epa_exemption %>%
    filter(`Fiscal Year` == "2018/2019") %>%
    filter(Exemption %in% c(5600,7000)),
  fillColor = "blue",
  color = "black",
  weight = 0.5,
  fillOpacity = 1
)
```

