---
title: "Assingment 1"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)
library(remotes)
install_github("yonghah/esri2sf")
library(esri2sf)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

epa_zoning <- esri2sf("https://services8.arcgis.com/0IC8hha3hgQkmGoa/arcgis/rest/services/EastPaloAltoZoning_2021_WFL1/FeatureServer/1")

smc_exemption <- read_csv("https://datahub.smcgov.org/api/views/pmvw-bs84/rows.csv?accessType=DOWNLOAD")
```


```{r}
import_census <- function(year) {
  listCensusMetadata(
    name = str_c(year, "/acs/acs5")
  )
}
```

```{r}
years <- 2015:2019
acs_vars <- map(years, import_census)
```

```{r}
acs_vars <- acs_vars %>%
  set_names(2015:2019) %>%
  bind_rows(.id = "year")
```

```{r}
process_census_data <- function(data, labels) {
  data %>%   
    mutate(
      placeID = paste0(state,place)
    ) %>% 
    select(!c(state, place, GEO_ID, NAME) & !ends_with(c("EA","MA","M"))) %>%
    pivot_longer(
      ends_with("E"),
      names_to = "variable",
      values_to = "estimate"
    ) %>%
    left_join(
      labels %>%
        select(name, label),
      by = (c("variable" = "name"))
    ) %>%
    separate(
      label,
      into = c(NA,NA,"income_range","percentage"),
      sep = "!!"
    ) %>%
    filter(
      !is.na(percentage)
    )
}
```

```{r}
rent_burden <- function(year) {
  census_renters_labels <- acs_vars %>%
    filter(
      .data$year == .env$year,
      group %in% c("B25074")
    )

  getCensus(
    name = "acs/acs5",
    vintage = year,
    region = "place:20956",
    regionin = "state:06",
    vars = "group(B25074)"
  ) %>%
    process_census_data(labels = census_renters_labels)
}
```

```{r}
owner_burden <- function(year){
    census_owner_labels <- acs_vars %>%
    filter(
      .data$year == .env$year,
      group %in% c("B25095")
    )
  getCensus(
    name = "acs/acs5",
    vintage = year,
    region = "place:20956",
    regionin = "state:06",
    vars = "group(B25095)"
  ) %>%
    process_census_data(labels = census_owner_labels)
}

owner_burden
```

#test for margin of error
```{r}
  census_owner_labels <- acs_vars %>%
    filter(
      year == 2019,
      group %in% c("B25095")
    )
 try <- getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "place:20956",
    regionin = "state:06",
    vars = "group(B25095)"
  ) %>% 
    mutate(
      placeID = paste0(state,place)
    ) %>% 
    select(!c(state, place, GEO_ID, NAME) ) %>%
    pivot_longer(
      ends_with("E"),
      names_to = "variable",
      values_to = "estimate"
    ) %>%
    left_join(
      census_owner_labels %>%
        select(name, label),
      by = (c("variable" = "name"))
    ) %>%
    separate(
      label,
      into = c(NA,NA,"income_range","percentage"),
      sep = "!!"
    ) %>%
    filter(
      !is.na(percentage)
    )
```


```{r}
rent_burdens <- map(years, rent_burden) %>%
  set_names(years) %>%
  bind_rows(.id = "year") %>% 
  mutate(occupant_type = "renter")
```

```{r}
owner_burdens <- map(years, owner_burden) %>%
  set_names(years) %>%
  bind_rows(.id = "year") %>% 
  mutate(occupant_type = "owner")
```

```{r}
percentage_calculator <- function(df){
  df %>%
    group_by(year, occupant_type) %>%
    mutate(
      rent_burdened = ifelse(
        percentage %in% c(
          "30.0 to 34.9 percent",
          "35.0 to 39.9 percent",
          "40.0 to 49.9 percent",
          "50.0 percent or more"
        ),
        estimate,
        NA
      )
    )  %>% 
    summarize(
      total_pop = sum(estimate, na.rm = T),
      total_burdened = sum(rent_burdened, na.rm = T)
    ) %>%
    mutate(
      percentage = total_burdened / total_pop,
    )
}
```

```{r comparison chart}
burden_chart <- rbind(
  percentage_calculator(owner_burdens), 
  percentage_calculator(rent_burdens)
  ) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = year,
      y = percentage*100,
      fill = occupant_type
    ),
    stat = "identity",
    position = "dodge"
  ) + 
  labs(
    x = "Year",
    y = "Percentage",
    title = "Housing Burden Comparison"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  theme_classic()

burden_chart
```

```{r}
owner_burdens2 <- map(2019, owner_burden) %>%
  set_names(2019) %>%
  bind_rows(.id = "year") %>% 
  mutate(occupant_type = "owner")

income_burden_percentage_calculator <- function(df){
  df %>%
    group_by(2019, occupant_type, income_range ) %>%
    mutate(
      rent_burdened = ifelse(
        percentage %in% c(
          "30.0 to 34.9 percent",
          "35.0 to 39.9 percent",
          "40.0 to 49.9 percent",
          "50.0 percent or more"
        ),
        estimate,
        NA
      )
    )  %>% 
    summarize(
      total_pop = sum(estimate, na.rm = T),
      total_burdened = sum(rent_burdened, na.rm = T)
    ) %>%
    mutate(
      percentage = total_burdened / total_pop,
    )
}

income_burden_percentage_calculator(owner_burdens)
```




## Second Analysis

```{r cars, include=FALSE}
epa_exemption <- smc_exemption %>% 
  mutate(
    APN = `Parcel Number` %>% 
      str_replace_all("-","")
  ) %>% 
  filter(APN %in% epa_zoning$APN) %>% 
  left_join(epa_zoning) %>% 
  # could have instead done right_join
  st_as_sf() %>% 
  filter(New_Zone == "R-LD")
```

```{r pressure}
leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = epa_exemption %>% 
      filter(`Fiscal Year` == "2018/2019"),
    fillColor = "yellow",
    color = "black",
    weight = 0.5
  ) %>%
addPolygons(
  data = epa_exemption %>%
    filter(`Fiscal Year` == "2018/2019") %>%
    filter(Exemption %in% c(5600,7000)),
  fillColor = "blue",
  color = "black",
  weight = 0.5,
  fillOpacity = 1
)
