---
title: "week 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tigris)
library(remotes)
library(sf)
library(leaflet)
library(readxl)
library(mapboxapi)

path <- ("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/NHTS/nhts17-caltrans-tsdc-download/") 

pois <- st_read("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/OSM/gis_osm_pois_a_free_1.shp")

mb_access_token("pk.eyJ1IjoiZGhiZGhiZGhiIiwiYSI6ImNreXRjbG5rejA1c2QybnJ6emJ3ams3NmwifQ.yMkBv9JKdM1b8InE8efcag", install = T)
```

```{r nhts data}
survey_household <- read_csv(paste0(path,"survey_household.csv"))

survey_person <- read.csv(paste0(path,"survey_person.csv")) # read_csv() appeared to trigger an error because of a formatting issue, so my second attempt is always the base R version of this function, read.csv(). It generally gives the same result.

survey_trip <- read_csv(paste0(path,"survey_trip.csv"))

survey_person_weights_7day <- read_csv(paste0(path,"survey_person_weights_7day.csv"))

nhts_lookup <- read_excel(
  paste0(path,"data_elements.xlsx"), 
  sheet = "Value Lookup"
)

person_weights <-
  survey_person %>% 
  left_join(
    survey_person_weights_7day %>% 
      select(
        sampno,
        perno,
        wttrdfin
      ),
    by = c("sampno","perno")
  )
```

```{r}

```


```{r}
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

cbsas <- core_based_statistical_areas(cb = T, progress_bar = F)

bay_cbsas <-
  cbsas %>%
  .[bay_counties %>% st_centroid(), ]

leaflet(bay_cbsas) %>% 
  addTiles() %>% 
  addPolygons(
    label = ~paste0(GEOID,": ",NAME)
  )
```
```{r}
bay_trips <-
  survey_trip %>% 
  left_join(
    survey_person,
    by = c("sampno","perno")
  ) %>% 
  left_join(
    survey_person_weights_7day %>% 
      select(
        sampno,
        perno,
        wttrdfin
      ),
    by = c("sampno","perno")
  ) %>% 
  left_join(
    survey_household %>% select(
      sampno,
      hh_cbsa
    )
  ) %>% 
  filter(hh_cbsa %in% bay_cbsas$GEOID)
```

```{r dictionary}
purpose_lookup <-
  nhts_lookup %>% 
  filter(NAME == "WHYTO") %>% 
  select(VALUE, LABEL) %>% 
  mutate(
    VALUE = as.numeric(VALUE),
    LABEL = factor(LABEL, levels = LABEL)
  )

purpose_lookup

mode_lookup <-
  nhts_lookup %>% 
  filter(NAME == "TRPTRANS") %>% 
  select(VALUE, LABEL) %>% 
  mutate(
    VALUE = as.numeric(VALUE),
    LABEL = factor(LABEL, levels = LABEL)
  )

mode_lookup
```

```{r}

```



